#操作系统基础环境初始化

user_name: "root"
yum_repo_proxy: "http://172.18.206.87:3142"

zabbix_server: "172.18.47.42
zabbix_agent_port: "20050""
zabbix_url: "http://zabbix.com/"

#文件仓库
artifactory_url: "http://172.18.206.191"

#docker仓库
docker_registry: "http://127.0.0.1"

#update kernel
elrepo_kernel: true

#kernel version mainline or longterm
kernel_version: "mainline"

# Deploy container engine
# Set false if you want to deploy container engine manually.
deploy_container_engine: false
container_manager: docker

salt_master: "172.18.32.30"
ntp_server: "time.exmaple.com"

#dns服务器 阿里云172.18.1.2，腾讯云172.18.1.2
dns_server: "172.18.1.2"

serverlog_kafka_fluent_bit: "172.18.206.231:9092,172.18.206.230:9092,172.18.206.232:9092"
serverlog_fluent_bit_topic: "serverlog"
