#- name: delete old tools
#  yum: name={{item}} state=absent
#  with_items:
#    - kernel-tools
#    - kernel-tools-libs

#- name: install mainline linux kerne
#  yum: name={{item}} state=latest
#  with_items:
#    - kernel-ml
#    - kernel-ml-devel
#    - kernel-ml-headers
#    - kernel-ml-tools
#  when: kernel_version == "mainline"

#- name: install longterm linux kernel
#  yum: name={{item}} state=latest
#  with_items:
#    - kernel-lt
#    - kernel-lt-devel
#    - kernel-lt-tools
#  when: kernel_version == "longterm"

- name: create blacklist for kernel modules
  copy:
    src: "{{ item }}"
    dest: "/etc/modprobe.d/"
  with_fileglob:
    - "modprobe.d/*.conf"

- name: create load list for kernel modules
  copy:
    src: "{{ item }}"
    dest: "/etc/modules-load.d/"
  with_fileglob:
    - "modules-load.d/*.conf"
