#name/dns cache for system
- name: install nscd
  yum: name={{item}} state=installed
  with_items:
    - nscd

- name: enable nscd service
  systemd:
    name: nscd
    state: started
    enabled: true
