galaxy_info:
  author: chengming
  description: shell scripts for initing nodes
  company: NOE
  license: MIT
  min_ansible_version: 2.1.2.0
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - jessie
    - name: Centos
      versions:
        - all
    - name: Fedora
      versions:
        - all
