- name: install python 2/3
  yum: name={{item}} state=installed
  with_items:
    - python-pip

- name: create pip config
  copy:
    src: "pip.conf"
    dest: "/etc/pip.conf"

- name: install dependencies for mountopts-module
  pip: name=fstab
