- name: install system utils
  yum: name={{item}} state=installed
  with_items:
    - gcc
    - gcc-c++
    - nc
    - lrzsz
    - bind-utils
    - telnet
    - lsof
    - gzip
    - htop
    - iftop
    - iotop
    - nethogs
    - iproute
    - tmux
    - net-tools
    - ipvsadm
    - git
    - unzip
    - perf
    - ltrace
    - dropwatch
    - trace-cmd 
    - iperf3
    - conntrack-tools
    - yum-plugin-versionlock

- name: delete system utils
  package: name={{item}} state=absent
  with_items:
    - irqbalance
