- name: install supervisor
  package: name={{item}} state=present
  with_items:
    - supervisor

- name: create supervisor config
  copy:
    src: "supervisord.conf"
    dest: "/etc/supervisord.conf"

- name: Make sure supervisord is running
  systemd:
    state: "started"
    name: "supervisor"
    enabled: true
