
variable "format" {
  type    = string
  default = "qcow2"
}

variable "password" {
  type    = string
  default = "anolisos"
}

variable "user" {
  type    = string
  default = "anuser"
}

locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }

source "qemu" "autogenerated_1" {
  #accelerator       = "kvm"
  boot_command      = ["<tab> text ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/centos-8-stream.ks<enter><wait>"]
  boot_wait         = "10s"
  disk_interface    = "virtio"
  disk_size         = 3072
  format            = "${var.format}"
  headless          = true
  http_directory    = "../http"
  iso_checksum      = "6e729887cdcd8e957795a03f4837a7cb"
  iso_url           = "http://mirrors.openanolis.cn/anolis/8.4/isos/GA/x86_64/AnolisOS-8.4-x86_64-dvd.iso"
  net_device        = "virtio-net"
  output_directory  = "build"
  qemuargs          = [["-m", "2048M"], ["-smp", "4"]]
  shutdown_command  = "echo '${var.password}'|sudo -S shutdown -h now"
  ssh_password      = "${var.password}"
  ssh_username      = "${var.user}"
  ssh_wait_timeout  = "60m"
  vnc_bind_address  = "0.0.0.0"
  vnc_use_password  = true
  vm_name           = "openanolis-amd64-${local.timestamp}.${var.format}"
}

build {
  sources = ["source.qemu.autogenerated_1"]

}
