- name: change grub boot menu
  lineinfile:
    path: "/etc/default/grub"
    regexp: "^GRUB_DEFAULT="
    line: "GRUB_DEFAULT=0"

- name: change kernel cmd boot parameters
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX="quiet nohz=off loglevel=3 rd.systemd.show_status=auto rd.udev.log_priority=3 selinux=0 cma=128M vsyscall=emulate nosoftlockup mce=off threadirqs noresume nmi_watchdog=0 vt.cur_default=50 transparent_hugepage=never cgroup_memory=nokmem swapaccount=1 nf_conntrack.acct=0 log_buf_len=2M idle=halt net.ifnames=0 biosdevname=0 mitigations=off noibrs nopti l1tf=off nomodeset nospec_store_bypass_disable noibpb spectre_v2_user=off spectre_v2=off kvm-intel.vmentry_l1d_flush=never no_timer_check noreplace-smp kvm-intel.nested=1 nosync iommu.strict=0 intel_iommu=on amd_iommu=on cryptomgr.notests rcu_nocbs=0-64 rcupdate.rcu_expedited=1 rcutree.kthread_prio=2 skew_tick=1"'

- name: clean old grub env
  file: path="/boot/grub2/grubenv" state=absent

- name: create grub env config
  shell: "grub2-editenv grubenv create"

#create grub2 menu
- name: apply grub config
  shell: "grub2-mkconfig  -o /boot/grub2/grub.cfg"
