- name: install python 3
  dnf: name={{item}} state=installed
  with_items:
    - python3
    - python3-pip

- name: create pip config
  copy:
    src: "pip.conf"
    dest: "/etc/pip.conf"

- name: install dependencies for mountopts-module
  pip: name=fstab
