#- name: copy apt source list
#  copy:
#    src: "zabbix.list"
#    dest: "/etc/apt/sources.list.d/"

#- name: copy gpg for zabbix
#  copy:
#    src: "zabbix-official-repo.gpg"
#    dest: "/etc/apt/trusted.gpg.d/"

- name: install zabbix agent
  package: name={{item}} state=present
  with_items:
    - zabbix-agent

- name: create zabbix agent config
  template:
    src: "zabbix_agentd.conf.j2"
    dest: "/etc/zabbix/zabbix_agentd.conf"

#- name: link zabbix_agentd.d dir
#  file:
#    src: "/etc/zabbix/zabbix_agentd.conf.d/"
#    path: "/etc/zabbix/zabbix_agentd.d"
#    state: link

- name: Make sure zabbix agent is running
  systemd:
    state: "restarted"
    name: "zabbix-agent"
    enabled: true
