#!/bin/bash
### BEGIN INIT INFO
# Provides: ecs_mq_rps_rfs
# Required-Start:    $local_fs $network
# Default-Start:  3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop ecs_mq_rps_rfs
# Description:  The ecs_mq_rps_rfs will be enable ecs multiqueue ,and enable rps and rfs.
### END INIT INFO

# This is an interactive program, we need the current locale

# Source function library.
. /etc/init.d/functions

# Check that we're a priviledged user
[ `id -u` = 0 ] || exit 0

prog="ecs_mq_rps_rfs"

start() {
	if [ -f /sbin/ecs_mq_rps_rfs ]; then
		/sbin/ecs_mq_rps_rfs
	fi
}

stop() {
	echo "stop"
}

#status() {
#}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
#  status)
#	status
#	;;
  restart)
	stop
	start
	;;
  *)
  echo $"Usage: $0 {start|stop|restart}"
        exit 2
esac

