- name: copy gpg keys
  copy:
    src: "{{ item }}"
    dest: "/etc/apt/trusted.gpg.d/"
  with_fileglob:
    - "apt/trusted.gpg.d/*.gpg"

#- name: create apt repo 
#  copy:
#    src: "apt/sources.list"
#    dest: "/etc/apt/sources.list"

- name: pinned docker-ce version
  copy:
    src: "apt/preferences.d/docker-ce"
    dest: "/etc/apt/preferences.d/docker-ce"

- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day
