- name: change grub boot menu
  lineinfile:
    path: "/etc/default/grub"
    regexp: "^GRUB_DEFAULT="
    line: "GRUB_DEFAULT=0"

- name: change kernel cmd boot parameters
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet nohz loglevel=3 rd.systemd.show_status=auto rd.udev.log_priority=3 systemd.unified_cgroup_hierarchy=0 scsi_mod.use_blk_mq=1 crashkernel=384M-2G:64M,2G-:128M  workqueue.power_efficient=0 domain cma=128M vsyscall=emulate mce=off threadirqs noresume nmi_watchdog=0 vt.cur_default=50 transparent_hugepage=never cgroup_enable=memory cgroup_memory=nokmem swapaccount=1 nf_conntrack.acct=0 log_buf_len=2M intel_pstate=disable processor.max_cstate=0 intel_idle.max_cstate=0 thermal.off=1 pcie_aspm=off cpufreq.off=1 idle=halt net.ifnames=0 biosdevname=0 mitigations=off noibrs nopti l1tf=off nomodeset nospec_store_bypass_disable noibpb spectre_v2_user=off spectre_v2=off kvm-intel.vmentry_l1d_flush=never no_timer_check noreplace-smp kvm-intel.nested=1 nosync iommu.strict=0 intel_iommu=on amd_iommu=on cryptomgr.notests rcu_nocbs=0-64 rcupdate.rcu_expedited=1 rcutree.kthread_prio=2 skew_tick=1"'

- name: clean old grub env
  file: path="/boot/grub/grubenv" state=absent

- name: create grub env config
  shell: "grub-editenv grubenv create"

#create grub2 menu
- name: apply grub config
  shell: "grub-mkconfig  -o /boot/grub/grub.cfg"
