- name: install python 2/3
  package: name={{item}} state=present
  with_items:
    - python3
    - python3-pip
    - python-pip

- name: create pip config
  copy:
    src: "pip.conf"
    dest: "/etc/pip.conf"
