- name:  modify kubelet config for systemd execstart
  lineinfile:
    dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: '^ExecStart='
    line: 'ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_SYSTEM_PODS_ARGS $KUBELET_NETWORK_ARGS $KUBELET_DNS_ARGS $KUBELET_AUTHZ_ARGS $KUBELET_CGROUP_ARGS $KUBELET_CERTIFICATE_ARGS $KUBELET_EXTRA_ARGS $KUBELET_UNSAFE_SYSCTLS'

- name:  modify kubelet config for systemd env
  lineinfile:
    dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    insertbefore: '^ExecStart='
    line: 'Environment="KUBELET_UNSAFE_SYSCTLS=--allowed-unsafe-sysctls=net.*"'
  notify:
    - apply kubelet
